version: "3.9"

services:
  dist-db:
    container_name: sportschool-db
    image: "postgres:15.2-bullseye" 
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      #external:internal
      - "5445:5432"
    volumes:
      - dist-db-sportsystem-volume:/var/lib/postgresql/data
      
volumes:
  dist-db-sportsystem-volume: